swagger: '2.0'
info:
  version: v1
  title: wecard
  description: A wecard API based on Swagger and built using Node.js
host: localhost
basePath: /
securityDefinitions:
  tokenAuth:
    type: basic
security:
  - tokenAuth: []
consumes:
  - application/json
paths:
  '/user':
    get:
      tags:
        - User
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
  '/namecard':
    get:
      tags:
        - Namecard
      summary: Get all Namecards of current user
      operationId: namecard_get
      produces:
        - application/json
        - text/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Namecard'
    post:
      tags:
        - Namecard
      summary: Create a Namecard
      operationId: namecard_create
      parameters:
        - $ref: '#/parameters/Namecard'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Namecard'
    put:
      tags:
        - Namecard
      summary: Update the Namecard
      operationId: namecard_update
      parameters:
        - $ref: '#/parameters/Namecard'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Namecard'
    delete:
      tags:
        - Namecard
      summary: Delete the Namecard
      operationId: namecard_delete
      parameters:
        - $ref: '#/parameters/Namecard'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Namecard'
  '/namecard/{id}':
    get:
      tags:
        - Namecard
      summary: Get the Namecard with the id
      operationId: namecard_getById
      parameters:
        - name: id
          in: path
          description: The Namecard id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Namecard'
    delete:
      tags:
        - Namecard
      summary: Delete the Namecard with the id
      operationId: namecard_deleteById
      parameters:
        - name: id
          in: path
          description: The Namecard id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Namecard'
  '/cardcase/{id}':
    get:
      tags:
        - Cardcase
      summary: Get the Cardcase with the id
      operationId: cardcase_getById
      parameters:
        - name: id
          in: path
          description: The Cardcase id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Cardcase'
  '/cardcase/{id}/item':
    get:
      tags:
        - Cardcase
      summary: Get all CardcaseItem belonging to the Cardcase with the id
      operationId: cardcaseitem_get
      parameters:
        - name: id
          in: path
          description: The Cardcase id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CardcaseItem'
    post:
      tags:
        - Cardcase
      summary: Create a CardcaseItem in Cardcase with the Id
      operationId: cardcaseitem_create
      parameters:
        - name: id
          in: path
          description: The Cardcase id
          required: true
          type: string
        - $ref: '#/parameters/CardcaseItem'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CardcaseItem'
  '/cardcase/item/{id}':
    delete:
      tags:
        - Cardcase
      summary: Delete the CardcaseItem with id
      operationId: cardcase_item_deleteById
      parameters:
        - name: id
          in: path
          description: The CardcaseItem id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CardcaseItem'
  '/group':
    get:
      tags:
        - Group
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
  '/group/{id}/member':
    get:
      tags:
        - Group
      summary: Get all GroupMember belonging to the Group with the Id
      operationId: groupmemeber_get
      parameters:
        - name: id
          in: path
          description: The Group id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/GroupMember'
  '/accessrequest':
    get:
      tags:
        - AccessRequest
      summary: Get all AccessRequest sent to current user
      operationId: accessreqeust_get
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/AccessRequest'
    put:
      tags:
        - AccessRequest
      summary: Update an AccessRequest
      operationId: accessreqeust_update
      parameters:
        - $ref: '#/parameters/AccessRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccessRequest'
  '/accesslevel/{card_id}':
    get:
      tags:
        - AccessLevel
      summary: Get Access of the specified id
      operationId: access_getByCardId
      parameters:
        - name: card_id
          in: path
          description: The card Id to be accessed
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccessLevel'
  '/accesslevel':
    post:
      tags:
        - AccessLevel
      summary: Create an AccessLevle
      operationId: accesslevel_create
      parameters:
        - $ref: '#/parameters/AccessLevel'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccessLevel'
    put:
      tags:
        - AccessLevel
      summary: Update an Access
      operationId: accesslevel_update
      parameters:
        - $ref: '#/parameters/AccessLevel'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccessLevel'
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
  Namecard:
    type: object
    properties:
      id:
        type: string
      user_id:
        type: string
  Group:
    type: object
    properties:
      id:
        type: string
  GroupMember:
    type: object
    properties:
      id:
        type: string
      user_id:
        type: string
  Cardcase:
    type: object
    properties:
      id:
        type: string
  CardcaseItem:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      cardcase_id:
        type: string
  AccessLevel:
    type: object
    properties:
      id:
        type: string
      RequestUserId:
        type: string
      TargetUserId:
        type: string
      Level:
        type: integer
  AccessRequest:
    type: object
    properties:
      id:
        type: string
      RequestUserId:
        type: string
      TargetUserId:
        type: string
parameters:
  Namecard:
    name: body
    in: body
    required: true
    description: The Namecard
    schema:
      $ref: '#/definitions/Namecard'
  CardcaseItem:
    name: body
    in: body
    required: true
    description: The Cardcase
    schema:
      $ref: '#/definitions/CardcaseItem'
  AccessRequest:
    name: body
    in: body
    required: true
    description: The AccessRequest
    schema:
      $ref: '#/definitions/AccessRequest'
  AccessLevel:
    name: body
    in: body
    required: true
    description: The AccessLevel
    schema:
      $ref: '#/definitions/AccessLevel'
